# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cowtech-lib}
  s.version = "1.9.6.5"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Shogun}]
  s.date = %q{2011-09-28}
  s.description = %q{A general purpose utility library.}
  s.email = %q{shogun_panda@me.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "cowtech-lib.gemspec",
    "lib/cowtech-lib.rb",
    "lib/cowtech-lib/console.rb",
    "lib/cowtech-lib/option_parser.rb",
    "lib/cowtech-lib/script.rb",
    "lib/cowtech-lib/shell.rb",
    "lib/cowtech-lib/version.rb"
  ]
  s.homepage = %q{http://github.com/ShogunPanda/cowtech-lib}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{A general purpose utility library.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<jeweler>, [">= 0"])
      s.add_runtime_dependency(%q<open4>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<open4>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<open4>, [">= 0"])
  end
end

